# Symbolic computation

In [1]:
import sympy as sym
import sympy.printing as printing

In [391]:
theta, phi, lamb, omega = sym.symbols('Theta Phi Lambda Omega')
alpha1, alpha2, gamma = sym.symbols("alpha_1 alpha_2 gamma")
torque_par, torque_per = sym.symbols("tau_1 tau_2")
K1, K2 = sym.symbols("K1 K2")
Hoe = sym.symbols("H_{oe}")
# energy = sym.Function("U")(theta, phi, lamb, omega)

In [392]:
"""
Theta, azimuth L1
Phi, inplane L1

Lambda, azimuth L1
Omega, inplane L2
"""

sinT = sym.sin(theta)
cosT = sym.cos(theta)

cosL = sym.cos(lamb)
sinL = sym.sin(lamb)

sinO = sym.sin(omega)
cosO = sym.cos(omega)

sinP = sym.sin(phi)
cosP = sym.cos(phi)

cosPO = sym.cos(phi - omega)
sinPO = sym.sin(phi - omega)

const1 = (gamma / Ms1) * (1 / (1 + alpha1**2))
const2 = (gamma / Ms2) * (1 / (1 + alpha2**2))

Ms1, Ms2 = sym.symbols("M_{s1} M_{s2}")
He1, He2, He3 = sym.symbols("H_{ext1} H_{ext2} H_{ext3}")
Hd11, Hd12, Hd13 = sym.symbols("H_{dip11} H_{dip12} H_{dip13}")
Hd21, Hd22, Hd23 = sym.symbols("H_{dip21} H_{dip22} H_{dip23}")
Hde11, Hde12, Hde13 = sym.symbols("H_{de11} H_{de12} H_{de13}")
Hde21, Hde22, Hde23 = sym.symbols("H_{de21} H_{de22} H_{de23}")

Hext = sym.Matrix([He1, He2, He3])
Hdip1 = sym.Matrix([Hd11, Hd12, Hd13])
Hdip2 = sym.Matrix([Hd21, Hd22, Hd23])
Hdemag1 = sym.Matrix([Hde11, Hde12, Hde13])
Hdemag2 = sym.Matrix([Hde21, Hde22, Hde23])

M1 = sym.Matrix([Ms1 * sinT * cosP, Ms1 * sinT * sinP, Ms1 * cosT])
M2 = sym.Matrix([Ms2 * sinL * cosO, Ms2 * sinL * sinO, Ms2 * cosL])

anisotropies = K1 * (cosT**2 + (sinT**2) *
                     (sinP**2)) + K2 * (cosL**2 + (sinL**2) * (sinO**2))
dipole = -M1.dot(Hdip2) - M2.dot(Hdip1)
demag = -M1.dot(Hdemag1) - M2.dot(Hdemag2)
ext = -M1.dot(Hext) - M2.dot(Hext)

energy = anisotropies + dipole + demag + ext
dUdP = sym.diff(energy, phi)
dUdT = sym.diff(energy, theta)
dUdO = sym.diff(energy, omega)
dUdL = sym.diff(energy, lamb)

In [393]:
energy

-H_{de11}*M_{s1}*sin(Theta)*cos(Phi) - H_{de12}*M_{s1}*sin(Phi)*sin(Theta) - H_{de13}*M_{s1}*cos(Theta) - H_{de21}*M_{s2}*sin(Lambda)*cos(Omega) - H_{de22}*M_{s2}*sin(Lambda)*sin(Omega) - H_{de23}*M_{s2}*cos(Lambda) - H_{dip11}*M_{s2}*sin(Lambda)*cos(Omega) - H_{dip12}*M_{s2}*sin(Lambda)*sin(Omega) - H_{dip13}*M_{s2}*cos(Lambda) - H_{dip21}*M_{s1}*sin(Theta)*cos(Phi) - H_{dip22}*M_{s1}*sin(Phi)*sin(Theta) - H_{dip23}*M_{s1}*cos(Theta) - H_{ext1}*M_{s1}*sin(Theta)*cos(Phi) - H_{ext1}*M_{s2}*sin(Lambda)*cos(Omega) - H_{ext2}*M_{s1}*sin(Phi)*sin(Theta) - H_{ext2}*M_{s2}*sin(Lambda)*sin(Omega) - H_{ext3}*M_{s1}*cos(Theta) - H_{ext3}*M_{s2}*cos(Lambda) + K1*(sin(Phi)**2*sin(Theta)**2 + cos(Theta)**2) + K2*(sin(Lambda)**2*sin(Omega)**2 + cos(Lambda)**2)

In [394]:
sym.simplify(energy)

-H_{de11}*M_{s1}*sin(Theta)*cos(Phi) - H_{de12}*M_{s1}*sin(Phi)*sin(Theta) - H_{de13}*M_{s1}*cos(Theta) - H_{de21}*M_{s2}*sin(Lambda)*cos(Omega) - H_{de22}*M_{s2}*sin(Lambda)*sin(Omega) - H_{de23}*M_{s2}*cos(Lambda) - H_{dip11}*M_{s2}*sin(Lambda)*cos(Omega) - H_{dip12}*M_{s2}*sin(Lambda)*sin(Omega) - H_{dip13}*M_{s2}*cos(Lambda) - H_{dip21}*M_{s1}*sin(Theta)*cos(Phi) - H_{dip22}*M_{s1}*sin(Phi)*sin(Theta) - H_{dip23}*M_{s1}*cos(Theta) - H_{ext1}*M_{s1}*sin(Theta)*cos(Phi) - H_{ext1}*M_{s2}*sin(Lambda)*cos(Omega) - H_{ext2}*M_{s1}*sin(Phi)*sin(Theta) - H_{ext2}*M_{s2}*sin(Lambda)*sin(Omega) - H_{ext3}*M_{s1}*cos(Theta) - H_{ext3}*M_{s2}*cos(Lambda) + K1*(sin(Phi)**2*sin(Theta)**2 + cos(Theta)**2) + K2*(sin(Lambda)**2*sin(Omega)**2 + cos(Lambda)**2)

In [395]:
anisotropies.args

(K1*(sin(Phi)**2*sin(Theta)**2 + cos(Theta)**2),
 K2*(sin(Lambda)**2*sin(Omega)**2 + cos(Lambda)**2))

In [396]:
dTheta = const1 * ((-1 / sinT)*dUdP - alpha1*dUdT -
                  (cosL * sinT - cosT * sinL * cosPO) *
                  (torque_par + alpha1 * torque_per) - (sinL * sinPO) *
                  (alpha1 * torque_par - torque_per))
# dTheta = sym.simplify(dTheta)

In [397]:
dTheta

1.25663706143667e-6*gamma*(-alpha_1*(-H_{de11}*M_{s1}*cos(Phi)*cos(Theta) - H_{de12}*M_{s1}*sin(Phi)*cos(Theta) + H_{de13}*M_{s1}*sin(Theta) - H_{dip21}*M_{s1}*cos(Phi)*cos(Theta) - H_{dip22}*M_{s1}*sin(Phi)*cos(Theta) + H_{dip23}*M_{s1}*sin(Theta) - H_{ext1}*M_{s1}*cos(Phi)*cos(Theta) - H_{ext2}*M_{s1}*sin(Phi)*cos(Theta) + H_{ext3}*M_{s1}*sin(Theta) + K1*(2*sin(Phi)**2*sin(Theta)*cos(Theta) - 2*sin(Theta)*cos(Theta))) + (alpha_1*tau_1 - tau_2)*sin(Lambda)*sin(Omega - Phi) - (alpha_1*tau_2 + tau_1)*(-sin(Lambda)*cos(Theta)*cos(Omega - Phi) + sin(Theta)*cos(Lambda)) - (H_{de11}*M_{s1}*sin(Phi)*sin(Theta) - H_{de12}*M_{s1}*sin(Theta)*cos(Phi) + H_{dip21}*M_{s1}*sin(Phi)*sin(Theta) - H_{dip22}*M_{s1}*sin(Theta)*cos(Phi) + H_{ext1}*M_{s1}*sin(Phi)*sin(Theta) - H_{ext2}*M_{s1}*sin(Theta)*cos(Phi) + 2*K1*sin(Phi)*sin(Theta)**2*cos(Phi))/sin(Theta))/(alpha_1**2 + 1)

In [398]:
sym.diff(dTheta, phi)

1.25663706143667e-6*gamma*(-alpha_1*(H_{de11}*M_{s1}*sin(Phi)*cos(Theta) - H_{de12}*M_{s1}*cos(Phi)*cos(Theta) + H_{dip21}*M_{s1}*sin(Phi)*cos(Theta) - H_{dip22}*M_{s1}*cos(Phi)*cos(Theta) + H_{ext1}*M_{s1}*sin(Phi)*cos(Theta) - H_{ext2}*M_{s1}*cos(Phi)*cos(Theta) + 4*K1*sin(Phi)*sin(Theta)*cos(Phi)*cos(Theta)) - (alpha_1*tau_1 - tau_2)*sin(Lambda)*cos(Omega - Phi) - (-alpha_1*tau_2 - tau_1)*sin(Lambda)*sin(Omega - Phi)*cos(Theta) - (H_{de11}*M_{s1}*sin(Theta)*cos(Phi) + H_{de12}*M_{s1}*sin(Phi)*sin(Theta) + H_{dip21}*M_{s1}*sin(Theta)*cos(Phi) + H_{dip22}*M_{s1}*sin(Phi)*sin(Theta) + H_{ext1}*M_{s1}*sin(Theta)*cos(Phi) + H_{ext2}*M_{s1}*sin(Phi)*sin(Theta) - 2*K1*sin(Phi)**2*sin(Theta)**2 + 2*K1*sin(Theta)**2*cos(Phi)**2)/sin(Theta))/(alpha_1**2 + 1)

In [399]:
sym.simplify(sym.diff(dTheta, theta))

1.0*gamma*(-1.25663706143667e-6*H_{de11}*M_{s1}*alpha_1*sin(Theta)*cos(Phi) - 1.25663706143667e-6*H_{de12}*M_{s1}*alpha_1*sin(Phi)*sin(Theta) - 1.25663706143667e-6*H_{de13}*M_{s1}*alpha_1*cos(Theta) - 1.25663706143667e-6*H_{dip21}*M_{s1}*alpha_1*sin(Theta)*cos(Phi) - 1.25663706143667e-6*H_{dip22}*M_{s1}*alpha_1*sin(Phi)*sin(Theta) - 1.25663706143667e-6*H_{dip23}*M_{s1}*alpha_1*cos(Theta) - 1.25663706143667e-6*H_{ext1}*M_{s1}*alpha_1*sin(Theta)*cos(Phi) - 1.25663706143667e-6*H_{ext2}*M_{s1}*alpha_1*sin(Phi)*sin(Theta) - 1.25663706143667e-6*H_{ext3}*M_{s1}*alpha_1*cos(Theta) + 5.02654824574668e-6*K1*alpha_1*cos(Phi)**2*cos(Theta)**2 - 2.51327412287334e-6*K1*alpha_1*cos(Phi)**2 - 2.51327412287334e-6*K1*sin(Phi)*cos(Phi)*cos(Theta) - 1.25663706143667e-6*alpha_1*tau_2*sin(Lambda)*sin(Theta)*cos(Omega - Phi) - 1.25663706143667e-6*alpha_1*tau_2*cos(Lambda)*cos(Theta) - 1.25663706143667e-6*tau_1*sin(Lambda)*sin(Theta)*cos(Omega - Phi) - 1.25663706143667e-6*tau_1*cos(Lambda)*cos(Theta))/(alpha_

In [281]:
dPhi = const1 * ((1 / sinT) * dUdT - (alpha1 / (sinT**2)) * dUdP + (1 / sinT) *
                (cosL * sinT - cosT * sinL * cosPO) *
                (alpha1 * torque_par - torque_per) 
                - (1/sinT)*(sinL*sinPO)*(torque_par + alpha1*torque_per) + alpha1*Ms*Hoe/sinT)
dPhi

gamma*(H_{oe}*M_s*alpha_1/sin(Theta) - alpha_1*(H_{de11}*M_{s1}*sin(Phi)*sin(Theta) - H_{de12}*M_{s1}*sin(Theta)*cos(Phi) + H_{dip21}*M_{s1}*sin(Phi)*sin(Theta) - H_{dip22}*M_{s1}*sin(Theta)*cos(Phi) + H_{ext1}*M_{s1}*sin(Phi)*sin(Theta) - H_{ext2}*M_{s1}*sin(Theta)*cos(Phi) + 2*K1*sin(Phi)*sin(Theta)**2*cos(Phi))/sin(Theta)**2 + (alpha_1*tau_1 - tau_2)*(-sin(Lambda)*cos(Theta)*cos(Omega - Phi) + sin(Theta)*cos(Lambda))/sin(Theta) + (alpha_1*tau_2 + tau_1)*sin(Lambda)*sin(Omega - Phi)/sin(Theta) + (-H_{de11}*M_{s1}*cos(Phi)*cos(Theta) - H_{de12}*M_{s1}*sin(Phi)*cos(Theta) + H_{de13}*M_{s1}*sin(Theta) - H_{dip21}*M_{s1}*cos(Phi)*cos(Theta) - H_{dip22}*M_{s1}*sin(Phi)*cos(Theta) + H_{dip23}*M_{s1}*sin(Theta) - H_{ext1}*M_{s1}*cos(Phi)*cos(Theta) - H_{ext2}*M_{s1}*sin(Phi)*cos(Theta) + H_{ext3}*M_{s1}*sin(Theta) + K1*(2*sin(Phi)**2*sin(Theta)*cos(Theta) - 2*sin(Theta)*cos(Theta)))/sin(Theta))/(M_{s1}*(alpha_1**2 + 1))

In [400]:
dLam = const2 * ((-1 / sinT)*dUdO - alpha2*dUdL +
                  (-sinL * cosT + sinT * cosL * cosPO) *
                  (torque_par + alpha2 * torque_per) + (sinL * sinPO) *
                  (alpha2 * torque_par + torque_per) + Ms*Hoe) 
dLam

1.25663706143667e-6*gamma*(H_{oe}*M_s - alpha_2*(-H_{de21}*M_{s2}*cos(Lambda)*cos(Omega) - H_{de22}*M_{s2}*sin(Omega)*cos(Lambda) + H_{de23}*M_{s2}*sin(Lambda) - H_{dip11}*M_{s2}*cos(Lambda)*cos(Omega) - H_{dip12}*M_{s2}*sin(Omega)*cos(Lambda) + H_{dip13}*M_{s2}*sin(Lambda) - H_{ext1}*M_{s2}*cos(Lambda)*cos(Omega) - H_{ext2}*M_{s2}*sin(Omega)*cos(Lambda) + H_{ext3}*M_{s2}*sin(Lambda) + K2*(2*sin(Lambda)*sin(Omega)**2*cos(Lambda) - 2*sin(Lambda)*cos(Lambda))) - (alpha_2*tau_1 + tau_2)*sin(Lambda)*sin(Omega - Phi) + (alpha_2*tau_2 + tau_1)*(-sin(Lambda)*cos(Theta) + sin(Theta)*cos(Lambda)*cos(Omega - Phi)) - (H_{de21}*M_{s2}*sin(Lambda)*sin(Omega) - H_{de22}*M_{s2}*sin(Lambda)*cos(Omega) + H_{dip11}*M_{s2}*sin(Lambda)*sin(Omega) - H_{dip12}*M_{s2}*sin(Lambda)*cos(Omega) + H_{ext1}*M_{s2}*sin(Lambda)*sin(Omega) - H_{ext2}*M_{s2}*sin(Lambda)*cos(Omega) + 2*K2*sin(Lambda)**2*sin(Omega)*cos(Omega))/sin(Theta))/(alpha_2**2 + 1)

In [401]:
dOmega = const2 * ((1 / sinT) * dUdL - (alpha2 / (sinL**2)) * dUdO - (1 / sinL) *
                (sinL * cosT - sinT *cosL * cosPO) *
                (torque_per - alpha2 * torque_par) 
                + (1/sinL)*(sinT*sinPO)*(torque_par - alpha2*torque_per) + alpha2*Ms*Hoe/sinL)
dOmega

1.25663706143667e-6*gamma*(H_{oe}*M_s*alpha_2/sin(Lambda) - alpha_2*(H_{de21}*M_{s2}*sin(Lambda)*sin(Omega) - H_{de22}*M_{s2}*sin(Lambda)*cos(Omega) + H_{dip11}*M_{s2}*sin(Lambda)*sin(Omega) - H_{dip12}*M_{s2}*sin(Lambda)*cos(Omega) + H_{ext1}*M_{s2}*sin(Lambda)*sin(Omega) - H_{ext2}*M_{s2}*sin(Lambda)*cos(Omega) + 2*K2*sin(Lambda)**2*sin(Omega)*cos(Omega))/sin(Lambda)**2 - (-alpha_2*tau_1 + tau_2)*(sin(Lambda)*cos(Theta) - sin(Theta)*cos(Lambda)*cos(Omega - Phi))/sin(Lambda) - (-alpha_2*tau_2 + tau_1)*sin(Theta)*sin(Omega - Phi)/sin(Lambda) + (-H_{de21}*M_{s2}*cos(Lambda)*cos(Omega) - H_{de22}*M_{s2}*sin(Omega)*cos(Lambda) + H_{de23}*M_{s2}*sin(Lambda) - H_{dip11}*M_{s2}*cos(Lambda)*cos(Omega) - H_{dip12}*M_{s2}*sin(Omega)*cos(Lambda) + H_{dip13}*M_{s2}*sin(Lambda) - H_{ext1}*M_{s2}*cos(Lambda)*cos(Omega) - H_{ext2}*M_{s2}*sin(Omega)*cos(Lambda) + H_{ext3}*M_{s2}*sin(Lambda) + K2*(2*sin(Lambda)*sin(Omega)**2*cos(Lambda) - 2*sin(Lambda)*cos(Lambda)))/sin(Theta))/(alpha_2**2 + 1)

In [303]:
# dM = sym.Matrix([
#     [
#         sym.diff(dTheta, theta),
#         sym.diff(dTheta, phi),
#         sym.diff(dTheta, lamb),
#         sym.diff(dTheta, omega)
#     ],
#     [
#         sym.diff(dPhi, theta),
#         sym.diff(dPhi, phi),
#         sym.diff(dPhi, lamb),
#         sym.diff(dPhi, omega)
#     ],
#     [
#         sym.diff(dLam, theta),
#         sym.diff(dLam, phi),
#         sym.diff(dLam, lamb),
#         sym.diff(dLam, omega)
#     ],
#     [
#         sym.diff(dOmega, theta),
#         sym.diff(dOmega, phi),
#         sym.diff(dOmega, lamb),
#         sym.diff(dOmega, omega)
#     ]]
# )


dM = sym.Matrix([
    [
        sym.simplify(sym.diff(dTheta, theta)),
        sym.simplify(sym.diff(dTheta, phi)),
        sym.simplify(sym.diff(dTheta, lamb)),
        sym.simplify(sym.diff(dTheta, omega))
    ],
    [
        sym.simplify(sym.diff(dPhi, theta)),
        sym.simplify(sym.diff(dPhi, phi)),
        sym.simplify(sym.diff(dPhi, lamb)),
        sym.simplify(sym.diff(dPhi, omega))
    ],
    [
        sym.simplify(sym.diff(dLam, theta)),
        sym.simplify(sym.diff(dLam, phi)),
        sym.simplify(sym.diff(dLam, lamb)),
        sym.simplify(sym.diff(dLam, omega))
    ],
    [
        sym.simplify(sym.diff(dOmega, theta)),
        sym.simplify(sym.diff(dOmega, phi)),
        sym.simplify(sym.diff(dOmega, lamb)),
        sym.simplify(sym.diff(dOmega, omega))
    ]]
)

In [314]:
dM

Matrix([
[                                                                                                                                                                                    -gamma*(K1*(sin(2*Phi - Theta) + sin(2*Phi + Theta)) + 2*alpha_1*(H_{de11}*M_{s1}*sin(Theta)*cos(Phi) + H_{de12}*M_{s1}*sin(Phi)*sin(Theta) + H_{de13}*M_{s1}*cos(Theta) + H_{dip21}*M_{s1}*sin(Theta)*cos(Phi) + H_{dip22}*M_{s1}*sin(Phi)*sin(Theta) + H_{dip23}*M_{s1}*cos(Theta) + H_{ext1}*M_{s1}*sin(Theta)*cos(Phi) + H_{ext2}*M_{s1}*sin(Phi)*sin(Theta) + H_{ext3}*M_{s1}*cos(Theta) - 4*K1*cos(Phi)**2*cos(Theta)**2 + 2*K1*cos(Phi)**2) + 2*(alpha_1*tau_2 + tau_1)*(sin(Lambda)*sin(Theta)*cos(Omega - Phi) + cos(Lambda)*cos(Theta)))/(2*M_{s1}*(alpha_1**2 + 1)),                                                                                    -gamma*(H_{de11}*M_{s1}*cos(Phi) + H_{de12}*M_{s1}*sin(Phi) + H_{dip21}*M_{s1}*cos(Phi) + H_{dip22}*M_{s1}*sin(Phi) + H_{ext1}*M_{s1}*cos(Phi) + H_{ext2}*M_{s1}*sin(Ph

In [309]:
sym.simplify(sym.diff(dTheta, theta))
# sym.simplify(sym.diff(dTheta, phi)),
# sym.simplify(sym.diff(dTheta, lamb)),
# sym.simplify(sym.diff(dTheta, omega))

-gamma*(K1*(sin(2*Phi - Theta) + sin(2*Phi + Theta)) + 2*alpha_1*(H_{de11}*M_{s1}*sin(Theta)*cos(Phi) + H_{de12}*M_{s1}*sin(Phi)*sin(Theta) + H_{de13}*M_{s1}*cos(Theta) + H_{dip21}*M_{s1}*sin(Theta)*cos(Phi) + H_{dip22}*M_{s1}*sin(Phi)*sin(Theta) + H_{dip23}*M_{s1}*cos(Theta) + H_{ext1}*M_{s1}*sin(Theta)*cos(Phi) + H_{ext2}*M_{s1}*sin(Phi)*sin(Theta) + H_{ext3}*M_{s1}*cos(Theta) - 4*K1*cos(Phi)**2*cos(Theta)**2 + 2*K1*cos(Phi)**2) + 2*(alpha_1*tau_2 + tau_1)*(sin(Lambda)*sin(Theta)*cos(Omega - Phi) + cos(Lambda)*cos(Theta)))/(2*M_{s1}*(alpha_1**2 + 1))

In [402]:
sym.simplify(sym.diff(dPhi, phi))

-gamma*(-H_{de11}*M_{s1}*sin(Phi)*cos(Theta) + H_{de12}*M_{s1}*cos(Phi)*cos(Theta) - H_{dip21}*M_{s1}*sin(Phi)*cos(Theta) + H_{dip22}*M_{s1}*cos(Phi)*cos(Theta) - H_{ext1}*M_{s1}*sin(Phi)*cos(Theta) + H_{ext2}*M_{s1}*cos(Phi)*cos(Theta) - K1*(cos(2*Phi - 2*Theta) - cos(2*Phi + 2*Theta))/2 + alpha_1*(H_{de11}*M_{s1}*cos(Phi) + H_{de12}*M_{s1}*sin(Phi) + H_{dip21}*M_{s1}*cos(Phi) + H_{dip22}*M_{s1}*sin(Phi) + H_{ext1}*M_{s1}*cos(Phi) + H_{ext2}*M_{s1}*sin(Phi) - 4*K1*sin(Phi)**2*sin(Theta) + 2*K1*sin(Theta)) + (alpha_1*tau_1 - tau_2)*sin(Lambda)*sin(Omega - Phi)*cos(Theta) + (alpha_1*tau_2 + tau_1)*sin(Lambda)*cos(Omega - Phi))/(M_{s1}*(alpha_1**2 + 1)*sin(Theta))

In [337]:
pm_set

{'Ms1': 795774.715459,
 'Ms2': 795774.715459,
 'K1': 650000.0,
 'K2': 880000.0,
 'Hext': array([     0.        , 278521.15041065, 278521.15041065]),
 'Hdemag1': array([0., 0., 0.]),
 'Hdemag2': array([0., 0., 0.]),
 'Hdipole1': array([0., 0., 0.]),
 'Hdipole2': array([0., 0., 0.])}

In [15]:
def generate_bigass_matrix(x, Ms1, Ms2, K1, K2, Hext, Hdemag1, Hdemag2, Hdipole1,
                   Hdipole2, alpha1, alpha2, tau1, tau2, Hoe):
    theta, phi, lambda_, omega = x 
    gamma = 2.21e5
    sT = np.sin(theta)
    cT = np.cos(theta)

    sT2 = np.power(sT, 2)
    cT2 = np.power(cT, 2)

    sP = np.sin(phi)
    cP = np.cos(phi)

    sP2 = np.power(sP, 2)
    cP2 = np.power(cP, 2)

    sL = np.sin(lambda_)
    cL = np.cos(lambda_)
    sL2 = np.power(sL, 2)
    cL2 = np.power(cL, 2)

    sO = np.sin(omega)
    cO = np.cos(omega)
    sO2 = np.power(sO, 2)
    cO2 = np.power(cO, 2)

    TP = np.array([sT * cP, sP * sT, cT])

    OL = np.array([sL * cO, sL * sO, cL])

    H1 = Hdipole1 + Hdemag1 + Hdipole2
    H2 = Hdipole2 + Hdemag2 + Hdipole1

    # dTheta
    dTdt = K1*(np.sin(2*phi-theta)+np.sin(2*phi+theta)) + \
          2*alpha1*Ms1*(sum(Hdemag1*TP) + sum(Hdipole2*TP) + sum(Hext*TP)) + \
          2*alpha1*Ms1*(-4*K1*cP2*cT2 + 2*K1*cP2) + \
          2*(alpha1*tau2 + tau1)*(sL*sT*np.cos(omega-phi)+cL*cT)
    dTdt = -gamma * dTdt / (2 * Ms1 * (alpha1**2 + 1))

    x = sum(np.array([cP, sP, 0])*H1*Ms1)
    x2 = sum(np.array([sP, cP, 0])*H1*Ms1)
    dTdp = x + \
         -2*K1*(2*sP2 - 1)*sT + \
        alpha1*cT*x2 + \
        alpha1*cT*(K1*np.cos(2*phi - theta) - np.cos(2*phi-theta)) + \
        (alpha1*tau1 - tau2)*sL*np.cos(omega-theta) - \
        (alpha1*tau2 + tau1)*sL*np.sin(omega-phi)*cT

    dTdp = -gamma * dTdp / (Ms1 * (alpha1**2 + 1))

    dTdl = (alpha1*tau1- tau2)*np.sin(omega-phi)*cL + \
          (alpha1*tau2 + tau1)*(sL*sT + cL*cT*np.cos(omega-phi))
    dTdl = gamma * dTdl / (Ms1 * (alpha1**2 + 1))

    dTdo = (alpha1*tau1 - tau2)*np.cos(omega-phi) - \
          (alpha1*tau2 + tau1)*np.sin(omega-phi)*cT
    dTdo = gamma * sL * dTdo / (Ms1 * (alpha1**2 + 1))

    # dPhi
    x = sum(
        np.array([sP * cT * alpha1, cP, -alpha1 * cP * cT + sP]) * Ms1 * H1)
    dPdt = x - Hoe*Ms1*alpha1*cT + 2*K1*np.power(sT, 3)*cP2 + \
           alpha1*tau1*sL*np.cos(omega-phi) - \
           alpha1*tau2*sL*np.sin(omega-phi)*cT - \
           tau1*sL*np.sin(omega - phi)*cT - tau2*sL*np.cos(omega-phi)

    dPdt = gamma * dPdt / (Ms1 * (alpha1**2 + 1) * sT2)

    x = sum(np.array([-sP * cT, cP * cT, 0]) * Ms1 * H1)
    x2 = sum(np.array([cP, sP, 0]) * Ms1 * H1)
    dPdp = x - 0.5*K1*(np.cos(2*phi-2*theta) - np.cos(2*phi+2*theta)) + \
           alpha1*(x2 - 4*K1*sP2*sT + 2*K1*sT) + \
           (alpha1*tau1- tau2)*sL*np.sin(omega-phi)*cT + (alpha1*tau2 + tau1)*sL*np.cos(omega-theta)

    dPdp = -gamma * dPdp / (Ms1 * (alpha1**2 + 1) * sT)

    dPdl = (alpha1*tau1 - tau2)*sL*sT + cL*cT*np.cos(omega-phi) - \
           (alpha1*tau2 + tau1)*np.sin(omega-phi)*cL
    dPdl = -gamma * dPdl / (Ms1 * (alpha1**2 + 1) * sT)

    dPdo = (alpha1*tau1 - tau2)*np.sin(omega-phi)*cT + \
           (alpha1*tau2 + tau1)*np.cos(omega-phi)
    dPdo = gamma * dPdo * sL / (Ms1 * (alpha1**2 + 1) * sT)

    # dLam
    x = sum(np.array([sO, -cO, 0]) * H2 * Ms2)
    dLdt = (alpha2*tau2 + tau1)*(sL*sT + cL*cT*np.cos(omega-phi))*sT2 + \
           (x + 0.5*K2*(np.cos(lambda_ - 2*omega) - np.cos(lambda_ + 2*omega)))*sL*cT
    dLdt = gamma * dLdt / (Ms2 * (alpha2**2 + 1) * sT2)

    dLdp = (alpha2*tau1 + tau2)*sL*np.cos(omega-phi) + \
           (alpha2*tau2 + tau1)*sT*np.sin(omega-phi)*cL

    dLdp = gamma * dLdp / (Ms2 * (alpha2**2 + 1))

    x = sum(np.array([sO * cL, -cL * cO, 0]) * H2 * Ms2)
    x2 = sum(np.array([sL * cO, sL * sO, cL]) * H2 * Ms2 * alpha2)
    dLdl = x + x2 + 0.5*K2*(np.cos(2*lambda_ - 2*omega) - np.cos(2*lambda_ + 2*omega)) -  \
           sT*(2*alpha2*K2*(2*cL2 - 1)*cO2 + \
           (alpha2*tau1 + tau2)*np.sin(omega - phi)*cL + \
           (alpha2*tau2 + tau1)*(sL*sT*np.cos(omega-phi) + cL*cT))
    dLdl = -gamma * dLdl / (Ms2 * (alpha2**2 + 1) * sT)

    x = sum(np.array([sL * cO, sL * sO, 0]) * H2 * Ms2)
    x2 = sum(np.array([sO, -cO, 0]) * H2 * Ms2)
    dLdo = x - 2*K2*sL2*sO2 + \
          sT*alpha2*cL*(x2 + K2*(np.cos(lambda_ - 2*omega) - np.cos(lambda_ + 2*omega))) + \
          (alpha2*tau1 + tau2)*sL*np.cos(omega-phi)*sT + \
          (alpha2*tau2 + tau1)*sT*np.sin(omega- phi)*cL*sT
    dLdo = -gamma * dLdl / (Ms2 * (alpha2**2 + 1) * sT)

    # dOmega
    x = sum(np.array([cO, sO, 0]) * H2 * Ms2)
    x2 = sum(np.array([sO, -cO, 0]) * H2 * Ms2)
    dOdo = -alpha2*(x - 4*K2*sL*sO2 + 2*K2*sL)*sT - \
           (-(alpha2*tau1 - tau2)*np.sin(omega-phi)*cL - (alpha2*tau2 - tau1)*np.cos(omega - phi))*sT2 + \
           (x2 + K2*(np.cos(lambda_ - 2*omega) - np.cos(lambda_ + 2*omega)))
    dOdo = gamma * sL * cL * dOdo / (Ms2 * (alpha2**2 + 1) * sL * sT)

    x = sum(np.array([cL * cO, sO * cL, -sL]) * H2 * Ms2)
    dOdt = (alpha2*tau1 - tau2)*(sL*sT + cL*cT*np.cos(omega-phi))*sT2 - \
           (alpha2*tau2 - tau1)*np.sin(omega-phi)*cT*sT2 + \
           2*K2*sL*cL*cL2
    dOdt = -gamma * dOdt * sL * cT / (Ms2 * (alpha2**2 + 1) * sL * sT2)


    dOdp = (alpha2*tau1 - tau2)*np.sin(omega-phi)*cL + \
           (alpha2*tau2 - tau1)*np.cos(omega-phi)*sT
    dOdp = -gamma * dOdp / (Ms2 * (alpha2**2 + 1) * sL)

    x = sum(np.array([sO, cO, 0]) * H2 * Ms2)
    x2 = sum(np.array([sL * cO, sL * sO, cL]) * H2 * Ms2)
    dOdl = 2*sT*cL*alpha2*(x + 0.5*K2*(np.cos(lambda_-2*omega)-np.cos(lambda_+2*omega))) + \
           (alpha2*tau1 - tau2)*(sL*sT*np.cos(omega-phi) + cL*cT)*sL*sT - \
           (alpha2*(x + K2*(np.cos(lambda_-2*omega)-np.cos(lambda_+2*omega))) + \
           (alpha2*tau1 - tau2)*(sL*cT - sT*cL*np.cos(omega-phi)) + \
           (alpha2*tau2 - tau1)*sT*np.sin(omega-phi))*sT*cL + \
           (x2 - 2*K2*(2*cL2 - 1)*cO2)*sL2

    dOdl = gamma * (dOdl) / (Ms2 * (alpha2**2 + 1) * sL2 * sT)
    
    
    BAM = np.array([
        [dTdt, dTdp, dTdl, dTdo],
        [dPdt, dPdp, dPdl, dPdo],
        [dLdt, dLdp, dLdl, dLdo],
        [dOdt, dOdp, dOdl, dOdo]
    ], dtype=np.float64)
    
#     BAM = BAM.astype(np.float64)
    print(BAM)
    return np.linalg.eig(BAM)

In [19]:
final_pm = deepcopy(pm_set)
final_pm["Hoe"] = 3978.87
final_pm["tau1"] = 0.0
final_pm["tau2"] = 0.0
final_pm["alpha1"] = 0.3
final_pm["alpha2"] = 0.3

eigenvalues, eivenvectors = generate_bigass_matrix(res.x, **final_pm)

[[ 2.02134546e+10 -4.96832026e+04  0.00000000e+00 -0.00000000e+00]
 [-7.02791161e+41 -9.93665581e+04  1.04024298e+15  0.00000000e+00]
 [ 0.00000000e+00 -0.00000000e+00  3.43167815e+25  3.56977909e+40]
 [ 1.83082764e+21  0.00000000e+00 -1.14387441e+26  3.29496199e-11]]


In [20]:
eigenvalues

array([ 1.86860685e+23+0.00000000e+00j, -1.86860685e+23+0.00000000e+00j,
        1.71583908e+25+2.02073723e+33j,  1.71583908e+25-2.02073723e+33j])

In [21]:
eivenvectors

array([[ 2.65883659e-19+0.00000000e+00j,  2.65883659e-19+0.00000000e+00j,
         1.26568225e-47-5.48137768e-54j,  1.26568225e-47+5.48137768e-54j],
       [-1.00000000e+00+0.00000000e+00j,  1.00000000e+00+0.00000000e+00j,
         4.37110925e-27-5.14783893e-19j,  4.37110925e-27+5.14783893e-19j],
       [ 2.04107924e-42+0.00000000e+00j, -2.04107924e-42+0.00000000e+00j,
         1.00000000e+00+0.00000000e+00j,  1.00000000e+00-0.00000000e+00j],
       [-3.76158192e-37+0.00000000e+00j,  3.76158192e-37+0.00000000e+00j,
        -4.80656935e-16+5.66067865e-08j, -4.80656935e-16-5.66067865e-08j]])

# Solver

In [3]:
import numpy as np
M = np.array([0.2, 0.5, 0.6])
Hext = np.array([120, 0, 2])
N = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]])
M*Hext, N@M, M@N

(array([24. ,  0. ,  1.2]), array([0.7, 0.5, 0.6]), array([0.2, 0.7, 0.6]))

In [8]:
from scipy.optimize import minimize

MAGNETIC_PERMEABILITY = 12.57e-7
TtoAm = 795774.715459


def to_radian(angle):
    return angle * (np.pi / 180)


def get_tensor_interaction(M, N):
    return N @ M


def cartiesian_from_spherical(r, inplane, azimuth):
    return np.array([
        r * np.sin(azimuth) * np.cos(inplane),
        r * np.sin(azimuth) * np.sin(inplane), r * np.cos(azimuth)
    ])


def energy_cost_fn(x, Ms1, Ms2, K1, K2, Hext, Hdemag1, Hdemag2, Hdipole1,
                   Hdipole2):
    theta, phi, lambda_, omega = x
    sT = np.sin(theta)
    cT = np.cos(theta)

    sP = np.sin(phi)
    cP = np.cos(phi)

    sL = np.sin(lambda_)
    cL = np.cos(lambda_)

    sO = np.sin(omega)
    cO = np.cos(omega)

    TP = np.array([sT * cP, sP * sT, cT])

    OL = np.array([sL * cO, sL * sO, cL])

    A1 = K1 * (np.power(cT, 2) + np.power(sT, 2) * np.power(sP, 2))
    A2 = K2 * (np.power(cL, 2) + np.power(sL, 2) * np.power(sO, 2))

    cost = A1 + A2
    for H, M, A in zip([Hdemag1, Hdemag2, Hdipole1, Hdipole2, Hext, Hext],
                       [Ms1, Ms2, Ms2, Ms1, Ms1, Ms2],
                       [TP, OL, OL, TP, TP, OL]):
        cost -= np.sum(H * M * A)

    return cost


def gradient_vector_U(Ms, K, Hext, Hdemag, Hdipole, inplane_angle,
                      azimuth_angle):
    """
    [inplane, azimuth],
    [phi, theta],
    [omega, lambda]
    """
    K_gradient = np.array([
        2 * K * np.sin(azimuth_angle) * np.power(np.sin(inplane_angle), 2) *
        np.cos(inplane_angle), 2 * K * np.sin(inplane_angle) *
        np.cos(inplane_angle) * (np.power(np.sin(azimuth_angle), 2) - 1)
    ])

    # virtually the same types of interaction -- dipole & demag
    Hdemag_gradient = np.array([
        Hdemag[0] * np.sin(inplane_angle) * np.sin(azimuth_angle) -
        Hdemag[1] * np.sin(azimuth_angle) * np.cos(inplane_angle),
        -Hdemag[0] * np.cos(inplane_angle) * np.cos(azimuth_angle) -
        Hdemag[1] * np.sin(inplane_angle) * np.cos(azimuth_angle) +
        Hdemag[2] * np.sin(azimuth_angle)
    ]) * Ms

    Hdip_gradient = np.array([
        Hdipole[0] * np.sin(inplane_angle) * np.sin(azimuth_angle) -
        Hdipole[1] * np.sin(azimuth_angle) * np.cos(inplane_angle),
        -Hdipole[0] * np.cos(inplane_angle) * np.cos(azimuth_angle) -
        Hdipole[1] * np.sin(inplane_angle) * np.cos(azimuth_angle) +
        Hdipole[2] * np.sin(azimuth_angle)
    ]) * Ms

    Hext_gradient = np.array([
        Hext[0] * np.sin(inplane_angle) * np.sin(azimuth_angle) -
        Hext[1] * np.sin(azimuth_angle) * np.cos(inplane_angle),
        -Hext[0] * np.cos(inplane_angle) * np.cos(azimuth_angle) -
        Hext[1] * np.sin(inplane_angle) * np.cos(azimuth_angle) +
        Hext[2] * np.sin(azimuth_angle)
    ]) * Ms

    return K_gradient + Hdemag_gradient + Hdip_gradient + Hext_gradient


def jac(x, Ms1, Ms2, K1, K2, Hext, Hdemag1, Hdemag2, Hdipole1, Hdipole2):
    theta, phi, lambda_, omega = x
    gradA = gradient_vector_U(Ms1, K1, Hext, Hdemag1, Hdipole2, phi, theta)
    gradB = gradient_vector_U(Ms2, K2, Hext, Hdemag2, Hdipole1, omega, lambda_)

    return [*gradA, *gradB]


Ndemag = np.array([[0, 0., 0.], [0., 0, 0.], [0., 0., 1.]])
# Ndipole = np.array([[5.57049776248663e-4, 0., 0.],
#                     [0., 0.00125355500286346, 0.],
#                     [0., 0.0, -0.00181060482770131]])
Ndipole = np.array([[0, 0., 0.], [0., 0, 0.], [0., 0.0, 0]])

phi = to_radian(10)  # inplane
theta = to_radian(30)

omega = to_radian(40)  # inplane
lambda_ = to_radian(80)
Ms1 = Ms2 = 1 * TtoAm

Ms1v = cartiesian_from_spherical(Ms1, phi, theta)
Ms2v = cartiesian_from_spherical(Ms2, omega, lambda_)


pm_set = {
    'Ms1': Ms1,
    'Ms2': Ms2,
    'K1': 650e3,
    'K2': 880e3,
    'Hext': np.array([0, 1, 1]) * 0.35 * TtoAm,
    'Hdemag1': get_tensor_interaction(Ms1v, Ndemag),  #/ MAGNETIC_PERMEABILITY,
    'Hdemag2': get_tensor_interaction(Ms2v, Ndemag),  #/ MAGNETIC_PERMEABILITY
    'Hdipole1': get_tensor_interaction(Ms1v,
                                       Ndipole),  #/ MAGNETIC_PERMEABILITY,
    'Hdipole2': get_tensor_interaction(Ms2v,
                                       Ndipole),  #/ MAGNETIC_PERMEABILITY,
}

start_set = {
    'theta': theta,
    'phi': phi,
    'lambda_': lambda_,
    'omega': omega,
}
x0 = list(start_set.values())
bounds = [(0, np.pi * 2) for i in range(len(x0))]
arg_set = tuple(pm_set.values())
print(len(arg_set), len(x0))
res = minimize(energy_cost_fn,
               x0,
               bounds=bounds,
               args=arg_set,
               jac=jac,
               tol=1e-4)
print(res)

9 4
      fun: -1101659635148.4153
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 5.42861652e-05, -1.88609588e-04,  5.42861652e-05, -8.12195756e-05])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 42
      nit: 1
     njev: 42
   status: 2
  success: False
        x: array([6.28318531, 0.        , 6.28318531, 0.        ])


In [7]:
import numpy as np
from copy import deepcopy

MAGNETIC_PERMEABILITY = 12.57e-7
TtoAm = 795774.715459
"""
        Spherical coords
        Theta -- azimuth angle, L1
        Phi -- inplane angle, L1
        Omega -- inplane angle, L2
        Lambda -- azimuth angle, L2
"""


def energy_cost_fn(theta, phi, lambda_, omega, Ms1, Ms2, K1, K2, Hext, Hdemag1,
                   Hdemag2, Hdipole1, Hdipole2):

    sT = np.sin(theta)
    cT = np.cos(theta)

    sP = np.sin(phi)
    cP = np.cos(phi)

    sL = np.sin(lambda_)
    cL = np.cos(lambda_)

    sO = np.sin(omega)
    cO = np.cos(omega)

    TP = np.array([sT * cP, sP * sT, cT])

    OL = np.array([sL * cO, sL * sO, cL])

    A1 = K1 * (np.power(cT, 2) + np.power(sT, 2) * np.power(sP, 2))
    A2 = K2 * (np.power(cL, 2) + np.power(sL, 2) * np.power(sO, 2))

    cost = A1 + A2
    for H, M, A in zip([Hdemag1, Hdemag2, Hdipole1, Hdipole2, Hext, Hext],
                       [Ms1, Ms2, Ms2, Ms1, Ms1, Ms2],
                       [TP, OL, OL, TP, TP, OL]):
        cost -= np.sum(H * M * A)

    return cost


def gradient_vector_U(Ms, K, Hext, Hdemag, Hdipole, inplane_angle,
                      azimuth_angle):
    """
    [inplane, azimuth],
    [phi, theta],
    [omega, lambda]
    """
    K_gradient = np.array([
        2 * K * np.sin(azimuth_angle) * np.power(np.sin(inplane_angle), 2) *
        np.cos(inplane_angle), 2 * K * np.sin(inplane_angle) *
        np.cos(inplane_angle) * (np.power(np.sin(azimuth_angle), 2) - 1)
    ])

    # virtually the same types of interaction -- dipole & demag
    Hdemag_gradient = np.array([
        Hdemag[0] * np.sin(inplane_angle) * np.sin(azimuth_angle) -
        Hdemag[1] * np.sin(azimuth_angle) * np.cos(inplane_angle),
        -Hdemag[0] * np.cos(inplane_angle) * np.cos(azimuth_angle) -
        Hdemag[1] * np.sin(inplane_angle) * np.cos(azimuth_angle) +
        Hdemag[2] * np.sin(azimuth_angle)
    ]) * Ms

    Hdip_gradient = np.array([
        Hdipole[0] * np.sin(inplane_angle) * np.sin(azimuth_angle) -
        Hdipole[1] * np.sin(azimuth_angle) * np.cos(inplane_angle),
        -Hdipole[0] * np.cos(inplane_angle) * np.cos(azimuth_angle) -
        Hdipole[1] * np.sin(inplane_angle) * np.cos(azimuth_angle) +
        Hdipole[2] * np.sin(azimuth_angle)
    ]) * Ms

    Hext_gradient = np.array([
        Hext[0] * np.sin(inplane_angle) * np.sin(azimuth_angle) -
        Hext[1] * np.sin(azimuth_angle) * np.cos(inplane_angle),
        -Hext[0] * np.cos(inplane_angle) * np.cos(azimuth_angle) -
        Hext[1] * np.sin(inplane_angle) * np.cos(azimuth_angle) +
        Hext[2] * np.sin(azimuth_angle)
    ]) * Ms

    return K_gradient + Hdemag_gradient + Hdip_gradient + Hext_gradient


def gradientDescent(param_set,
                    Ndemag,
                    Ndipole,
                    layer='A',
                    num_iterations=100000,
                    lr=0.01,
                    w=10,
                    err=1e-2):
    """
    x = [inplane, azimuth]
    """
    if layer == 'A':
        Ms, K, Hext = param_set['Ms1'], param_set["K1"], param_set["Hext"]
        Hdipole, Hdemag, = param_set["Hdipole2"], param_set["Hdemag1"]
        x = np.array([param_set['phi'], param_set['theta']])
    elif layer == "B":
        Ms, K, Hext = param_set['Ms2'], param_set["K2"], param_set["Hext"]
        Hdipole, Hdemag, = param_set["Hdipole1"], param_set["Hdemag2"]
        x = np.array([param_set['omega'], param_set['lambda_']])
    else:
        raise ValueError("Unidentified layer")

    param_set_copy = deepcopy(param_set)
    last_cost = 0
    previous_grad = np.array([0.0, 0.0])
    previous_x = np.array([0., 0.])
    for i in range(num_iterations):

        cerr_normed = np.abs(np.linalg.norm(x - previous_x))
        if cerr_normed <= err:
            print(f"Reached the error: {cerr_normed}! Breaking the loop.")
            break

        gradA = gradient_vector_U(param_set['Ms1'], param_set["K1"], param_set["Hext"], 
                                  param_set["Hdemag1"], param_set["Hdipole2"], x[0], x[1])
        gradB = gradient_vector_U(param_set['Ms1'], param_set["K1"], param_set["Hext"], 
                                  param_set["Hdemag2"], param_set["Hdipole1"], x[1], x[2])
        
        grad = np.concat([gradA, gradB])
        grad_diff = grad - previous_grad
        grad_diff_norm = np.sum(np.power(grad_diff, 2))
        # Wolff conditions
        gamma = np.abs((x - previous_x).T * grad_diff) / grad_diff_norm
        previous_x = x
        previous_grad = grad
        x = x - gamma * grad
        if i % w == 0:
            print(f"{grad[0]:.2f}, {grad[1]:.2f}")
            if layer == 'A':
                param_set_copy['phi'] = x[0]
                param_set_copy['theta'] = x[1]

                Ms1v = cartiesian_from_spherical(Ms1, x[0], x[1])
                param_set_copy['Hdemag1'] = get_tensor_interaction(
                    Ms1v, Ndemag) #/ MAGNETIC_PERMEABILITY
                param_set_copy['Hdipole1'] = get_tensor_interaction(
                    Ms1v, Ndipole) # / MAGNETIC_PERMEABILITY
            else:
                param_set_copy['omega'] = x[0]
                param_set_copy['lambda_'] = x[1]

                Ms2v = cartiesian_from_spherical(Ms2, x[0], x[1])
                param_set_copy['Hdemag2'] = get_tensor_interaction(
                    Ms2v, Ndemag) / MAGNETIC_PERMEABILITY
                param_set_copy['Hdipole2'] = get_tensor_interaction(
                    Ms2v, Ndipole) / MAGNETIC_PERMEABILITY

            cost = energy_cost_fn(**param_set_copy)
            gamma_mag = np.linalg.norm(gamma)
            print(
                f"[{i}] Cost: {cost:.2f} -- diff {last_cost-cost:.2f}; err: {cerr_normed:.4f}; {gamma_mag:.4f}"
            )
            last_cost = cost
    return x

In [221]:
Ndemag = np.array([[0, 0., 0.], [0., 0, 0.],
                   [0., 0., 0.]])
# Ndipole = np.array([[5.57049776248663e-4, 0., 0.],
#                     [0., 0.00125355500286346, 0.],
#                     [0., 0.0, -0.00181060482770131]])
Ndipole = np.array([[0, 0., 0.],
                    [0., 0, 0.],
                    [0., 0.0, 0]])




phi = to_radian(10)  # inplane
theta = to_radian(30)

omega = to_radian(40)  # inplane
lambda_ = to_radian(80)

Ms1 = Ms2 = 1* TtoAm
Ms1v = cartiesian_from_spherical(Ms1, phi, theta)
Ms2v = cartiesian_from_spherical(Ms2, omega, lambda_)

param_set = {
    'theta': theta,
    'omega': omega,
    'phi': phi,
    'lambda_': lambda_,
    'Hext': np.array([0, 1, 1]) * 0.0 * TtoAm,
    'K1': 650e3,
    'K2': 880e3,
    'Ms1': Ms1,
    'Ms2': Ms2,
    'Hdipole1': get_tensor_interaction(Ms1v, Ndipole), #/ MAGNETIC_PERMEABILITY,
    'Hdipole2': get_tensor_interaction(Ms2v, Ndipole), #/ MAGNETIC_PERMEABILITY,
    'Hdemag1': get_tensor_interaction(Ms1v, Ndemag), #/ MAGNETIC_PERMEABILITY,
    'Hdemag2': get_tensor_interaction(Ms2v, Ndemag), #/ MAGNETIC_PERMEABILITY
}
print(phi, theta, omega, lambda_)
xstar = gradientDescent(param_set,
                Ndemag,
                Ndipole,
                layer='A',
                num_iterations=1000,
                lr=1e-4,
                err=1e-5,
                w=100)
xstar = xstar*180/np.pi

print(f"{xstar[0]:.2f} {xstar[1]:.2f}")

0.17453292519943295 0.5235987755982988 0.6981317007977318 1.3962634015954636
19302.13, -166734.82
[0] Cost: 559782.17 -- diff -559782.17; err: 0.5519; 0.0000
Reached the error: 9.904665934242075e-06! Breaking the loop.
0.00 89.34
